<style>
@media only screen and (max-width: 990px){
    
    .jefa{
        margin-left: 0px !important;
        margin-top: 178px !important;
        width: 200px;
    }
    .idea{
        margin-left: 30px !important;
        width: 120px;
        margin-top: 80px !important;
    }
    .Boton{
        margin-left: 150px !important;
    }
}
</style>
<img class="jefa" style="position: absolute; z-index: 100; margin-top: 146px; margin-left: 90px" width="220px" src="<?php echo $this->basePath() ?>/img/jefa.png" alt="">
<img class="idea" style="position: absolute; z-index: 100; margin-top: 30px; margin-left: 150px" width="150px" src="<?php echo $this->basePath() ?>/img/idea.png" alt="">
<div class="Banner" style="display:flex; justify-content:center; align-items:center; Position:relative; width:100%;background-image:url('<?php echo $this->basePath() ?>/img/mariangola.jpg');background-size: 100% 100%;background-position: 50%;background-repeat: no-repeat;position:relative; width:100%;height:500px;">
    
<div class="Boton" style=""><a style="color: white; font-size: 30px; font-weight: lighter; border: solid 2px white; border-radius: 50px; padding: 5px 20px 5px 20px;" href="<?php echo $this->url('stands',array('ano'=>$this->ANO, 'area'=>1));?>">Ingresar</a></div>
<div style="    position: absolute;margin-top: -150px;margin-left: 35%;"><img width="150px" src="<?php  echo $this->basePath() ?>/img/layout/logofif.png" alt=""> </div> 
</div>



<!--
<div class="Banner" style="display:flex;flex-direction: column; justify-content:flex-end; align-items:center; Position:relative; width:100%;background-image:url('<?php echo $this->basePath('img/publicidad-fi/'.$this->Publicidad->IMAGEN) ?>');background-size: 100% 100%;background-position: 50%;background-repeat: no-repeat;position:relative; width:100%;height:500px;">
<div style="margin-bottom: 100px"><img width="200px" src="<?php echo $this->basePath() ?>/img/layout/logo.png" alt=""> </div>
<div class="Boton" style=""><a style="color: white; font-size: 30px; font-weight: lighter; border: solid 2px white; border-radius: 50px; padding: 5px 20px 5px 20px;" href="<?php echo $this->url('salon',array('ano'=>$this->ANO));?>">Empezar</a></div>
</div>

 -->
