<style>
    body{
        background: white !important;
    }
    .main_bg{
        background-color: white !important;
        background: url('<?php echo $this->basePath() ?>/img/layout/marcas.png') !important;
        background-repeat: no-repeat !important;
        background-size: 100% 100% !important;
    }

    hr{
        background: blue;
        width: 100%;
        height: 7px
    }


</style>
        <!-- Carrusel n2,n3 Marcas -->
        <div id="marcas" style="" class="text-center">
        <div class="row">
        <div class="col-md-12 text-left">
        <h1 style="font-size: 60px;line-height: 0.3; margin-top:50px; font-weight: 900; color:blue; margin-bottom: 50px;">Marcas participantes</h1><hr>
        </div>
        </div>
        <div class="owl-2 owl-carousel text-center" style="margin-top: 40px;">

        <?php   foreach($this->Marcas as $mar){ ?>
              <a style="color: white; font-weight: bold; font-size: 18px;" href="<?php  echo $mar->WEB; ?>" target="_blank"><img src="<?php echo $this->basePath('img/Logo_Empresas/'); echo $mar->IMAGEN_ARCHIVO; ?>" style="width: 130px !important; margin:auto;" alt="">
                <p style="color:black"><?php  echo $mar->NOMBRE; ?></p></a> 
                      <?php  }   ?> 
        </div>
        <div class="owl-3 owl-carousel text-center" style="margin-top: 100px;">

           <?php   foreach($this->Marcas1 as $mar1){ ?>
              <a style="color: white; font-weight: bold; font-size: 18px;" href="<?php  echo $mar1->WEB; ?>" target="_blank"><img src="<?php echo $this->basePath('img/Logo_Empresas/'); echo $mar1->IMAGEN_ARCHIVO; ?>" style="width: 130px !important; margin:auto;" alt="">
                <p style="color:black"><?php  echo $mar1->NOMBRE; ?></p></a> 
                      <?php  }   ?> 
        </div></div>
        <!-- Carrusel n2,n3 Marcas -->
