<script>
$(document).ready(function() {

$('#DatosEnviar3').submit(function() {
	frm = $(this);
    btn = frm.find("#enviar");
    method = frm.attr("method");
    btn.attr("disabled", "disabled");
   $.ajax({
        url: frm.attr('action'),
        type: method,
        data: frm.serialize(),
        data: new FormData(this),
        contentType: false,
        cache: false,
        processData: false,
        success: function(data){
    		btn.removeAttr("disabled");
    		frm.find('.response').html(data).hide().slideDown();
    		},
    	error:function(data, msg){
    			btn.removeAttr("disabled");
    			frm.find('.response').html(data).hide().slideDown();
    			},
    });
    return false;

});

});

</script>
<style>
    .main_bg{
        background: url('<?php echo $this->basePath() ?>/img/layout/registro.jpg') !important;
        background-repeat: no-repeat !important;
        background-size: 100% 100% !important;
    }
    hr{
        background: white;
        width: 100%;
        height: 3px
    }

</style>
<?php
$this->form->setAttributes(array('id'=>'DatosEnviar3','action'=> $this->url('nregistro',array('ano'=>$this->ANO)),'method' => 'post'));
$this->form->prepare();

echo $this->form()->openTag($this->form);
?>
<div class="response"></div>
<div class="row">

    <div class="col-md-6">
    
<H1 class="text-center">Reg&iacute;strate</H1> <hr>
            <?php
        echo $this->formRow($this->form->get('NOMBRE'),null,null,'partial/formRow.phtml');
        echo $this->formRow($this->form->get('APELLIDOS'),null,null,'partial/formRow.phtml');
        echo $this->formRow($this->form->get('EMAIL'),null,null,'partial/formRow.phtml');
        echo $this->formRow($this->form->get('CLAVE'),null,null,'partial/formRow.phtml');?>
    </div>
    <div class="col-md-6" style="margin-top: 83px">
            <?php
        echo $this->formRow($this->form->get('CELULAR'),null,null,'partial/formRow.phtml');
        echo $this->formRow($this->form->get('TELEFONO'),null,null,'partial/formRow.phtml'); 
        echo $this->formRow($this->form->get('captcha'),null,null,'partial/formRow.phtml'); ?>
            
            <div style="display: none">
            <?php
        echo $this->formRow($this->form->get('ID_PAIS'),null,null,'partial/formRow.phtml');
        echo $this->formRow($this->form->get('CIUDAD'),null,null,'partial/formRow.phtml');
        echo $this->formRow($this->form->get('DIRECCION'),null,null,'partial/formRow.phtml');
        echo $this->formRow($this->form->get('RAZON_SOCIAL'),null,null,'partial/formRow.phtml');
        echo $this->formRow($this->form->get('NOMBRE_COMERCIAL'),null,null,'partial/formRow.phtml');
        echo $this->formRow($this->form->get('URL'),null,null,'partial/formRow.phtml');
        ?></div>
    </div>
            <style>
            </style>
        <div class="response"></div>
        <?php
        echo $this->formRow($this->form->get('enviar'),null,null,'partial/formRow.phtml');
        echo $this->form()->closeTag();
        ?>
</div>

