<style type="text/css">
<!--
}.arial13-azul {
	font-family: Arial, Helvetica, sans-serif;
	font-size: 13px;
	font-weight: normal;
	color: #3A7CB1;
	text-decoration: none;
}

.arial11-grey {
	font-family: Arial, Helvetica, sans-serif;
	font-size: 11px;
	font-weight: normal;
	color: #666666;
	text-decoration: none;
}
.h2 {
	font-family: Arial, Helvetica, sans-serif;
	font-size: 13px;
	font-weight: normal;
	color: #000000;
	text-decoration: bold;
}
-->
</style>
<table style="width:980px; height:100px; border: 0px; border-spacing: 0px; text-align:center; " >
  <tr>
    <td width="10" height="100" style="padding: 0px;">&nbsp;</td>
    <td width="322" height="100" align="left" valign="top" style="padding: 0px;">
    </td>
	<td width="530" height="100" align="right" valign="top" style="padding: 0px;">
	</td>
	<td width="10" style="padding: 0px;">&nbsp;</td>
  </tr>

</table>
<table style="width:555px; border: 0px; border-spacing: 0px;">
  <tr>
    <td width="35" style="padding: 0px;"></td>
    <td width="15" style="padding: 0px;">&nbsp;</td>
    <td width="405" style="padding: 0px;"><span class="arial13-azul">
    <strong>Contacto</strong></span><br/><br/>

	<br><span class="arial11-grey">Hola <?php echo $this->NOMBRE ?> La empresa <?php echo $this->EMPRESA; ?> te ha asignado una cita para la feria internacional de franquicias
	para el dia <?php echo $this->FECHA; ?> en el horario de <?php echo $this->HORA; ?> <br/> El codigo de tu cita es <?php echo $this->CODIGO; ?> </span><br/><br/>

	</td>
  </tr>
  <tr>
  	<td style="padding: 0px;"></td>
	<td style="padding: 0px;"></td>
    <td style="padding: 0px;"></td>
  </tr>
</table>
<table style="width:980px; height:100px; border: 0px; border-spacing: 0px;">

  <tr>

    <td>
    </td>


  </tr>
<tr>
<td>
</td>
</tr>
</table>