<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Fif3\Module'                        => __DIR__ . '/Module.php',
    'Fif3\Controller\IndexController' => __DIR__ . '/src/Fif3/Controller/IndexController.php',
    'Fif3Test\Framework\TestCase'        => __DIR__ . '/tests/Fif3/Framework/TestCase.php',
    'Fif3Test\SampleTest'                => __DIR__ . '/tests/Fif3/SampleTest.php',
);
